### ISSUE TITLE
chrome.storage.Storage.sync.set and get not working

### ISSUE THREAD

**Issue by dportabella** [lucidd/scala-js-chrome#47]
After executing this scalajs code: 
```
chrome.storage.Storage.sync.set(Map("key1" -> "value1"))
```

this javascript code 
```
chrome.storage.sync.get(undefined, function(result) { console.log(JSON.stringify(result)); });
```

shows `{"value1$5":"value1"}` instead of `{"key1":"value1"}`
is this a bug?

also, 
```
chrome.storage.Storage.sync.get(js.undefined).foreach(println)
```

throws an Error. why?

**Comment by raquo** [comment]
The facade was incorrect, it was fixed in https://github.com/lucidd/scala-js-chrome/commit/951875202f4c73f19624d7696375828dabbad71f

I don't know why the latest version is not published in Maven though.

**Comment by dportabella** [comment]
I try to use this version:
```
git clone https://github.com/lucidd/scala-js-chrome
cd scala-js-chrome
git checkout 9518752
sbt publishLocal
```

then, I update my project to use this version:
`libraryDependencies += "net.lullabyte" %%% "scala-js-chrome" % "603740b0290ed845cb34bbbf78e374aaac083781"
`

but I get this error when I building it:
```
$ sbt chromeUnpackedFast
Caused by: org.scalajs.core.ir.IRVersionNotSupportedException: This version (0.6.17) of Scala.js IR is not supported. Supported versions are: 0.6.0, 0.6.13, 0.6.3, 0.6.4, 0.6.6, 0.6.14, 0.6.8, 0.6.5, 0.6.15
```
I've tried adding this to my project/plugins.sbt, but I still get the same error.
`addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.15" force())
`

Any idea?

**Comment by dportabella** [comment]
@raquo , I don't manage to build and use a version of scala-js-chrome with the fix you mention. See https://github.com/lucidd/scala-js-chrome/issues/48 
Any idea?

**Comment by raquo** [comment]
@dportabella Not super sure, but looks like you need to upgrade the versions of sbt plugins in this project, at the very least scalajs and scalafmt. Watch out for any breaking changes though. Also you might need to drop support for scala 2.10 in build.sbt to achieve that, that's a very old version.

Oh and better start from the `master` branch, it's one year newer than the diff I linked to.

Really that's a question for the maintainer, I was only passing by, don't know the details of this project.

**Comment by dportabella** [comment]
Thanks @raquo .

I just gave up on building scala-js-chrome after spending two days on this.
Here it is my workaround in case someone is interested:

```
import chrome.utils.ErrorHandling.lastErrorOrValue

import scala.concurrent.{Future, Promise}
import scala.scalajs.js
import scala.scalajs.js.annotation.JSGlobal

object ChromeStorageSyncWrapper {
  def set(items: js.Dynamic): Future[Unit] = {
    val promise = Promise[Unit]()
    ChromeStorageSyncNative.set(items, js.Any.fromFunction0(() => {
      promise.complete(lastErrorOrValue(()))
    }))
    promise.future
  }

  def get(keys: js.UndefOr[js.Any] = js.undefined): Future[js.Dynamic] = {
    val promise = Promise[js.Dynamic]()
    ChromeStorageSyncNative.get(keys, (results: js.Dynamic) => {
      promise.complete(lastErrorOrValue(results))
    })
    promise.future
  }
}

@js.native
@JSGlobal("chrome.storage.sync")
object ChromeStorageSyncNative extends js.Object {
  def set(items: js.Dynamic, callback: js.UndefOr[js.Function0[_]] = js.undefined): Unit = js.native
  def get(keys: js.UndefOr[js.Any] = js.undefined, callback: js.Function1[js.Dynamic, _]): Unit = js.native
}

// Use:
ChromeStorageSyncWrapper.set(js.Dynamic.literal("key1" -> "value1", "key2" -> "value2"))
ChromeStorageSyncWrapper.get(js.Array("key1", "key2"))
```
